### ISSUE TITLE
blank page with response

### ISSUE THREAD

**Issue by alejandrogkl** [driftyco/custom-auth-examples#4]
Using the express examples i was able to register the user in Ionic but i am dont getting the response as success/fault in my application , the respose get printed in a blank page , the one that use the in app browser plugin

**Comment by ericb** [comment]
Have you taken out the redirect_uri as shown in the example code?

**Comment by alejandrogkl** [comment]
I really appreciate your response

After removing the redirect_uri i am getting the success responses in my app but not the fault ones

return res.status(401).send('auth error');

result in a blank page with "auth error" text

**Comment by ericb** [comment]
Ah okay, yeah we've gotten some complaints around that and will be addressing it in the next Auth update. This is related to https://github.com/driftyco/ionic-platform-web-client/issues/86
