### ISSUE TITLE
custom auth

### ISSUE THREAD

**Issue by alejandrogkl** [driftyco/custom-auth-examples#6]
How can i receive a token (or some data) in the success method of the custom auth process, i receive just the user.

My app consume an api that requiere that token in each request as an authorization header

Maybe i am not undestanding the concept but i dont like the idea of make another request to create/receive/store that token in the localStorage.

**Comment by imhoffd** [comment]
Good idea! I made an issue for this, which you can track here: https://github.com/driftyco/ionic-platform-issues/issues/95
