### ISSUE TITLE
I can't pass custom data when creating a token

### ISSUE THREAD

**Issue by De-Lac** [driftyco/custom-auth-examples#7]
I have my own server already working in production, with few existing users (about 30).
I'd like to integrate Ionic authentication, in a way that I have user details both on my server and on Ionic server. The reason is that if in the future I want to use just my server, or just Ionic server, I will have not problems.

In my server I do the following

```
var incomingToken = jwt.verify(req.query.token, mySharedSecret);
var email    = incomingToken.data.email;
var password = incomingToken.data.password;

my_custom_server_authentication(email, password)
    .then(function(user)
            {
              var ionic_user = {
                                           'user_id' : user._id,
                                           'custom' : user
                                         };
              var outgoingToken = jwt.sign(user, mySharedSecret);
               var url = redirectUri +
                     '&token=' + encodeURIComponent(outgoingToken) +
                     '&state=' + encodeURIComponent(state)+
            });
```

In this way the user gets created on the Ionic server, but just his ID is added, all the custom data is not. What should I do to add the whole user object?

**Comment by imhoffd** [comment]
@De-Lac Looks like we don't quite support this yet, but it will be easy enough to add! I will update this issue when I add the functionality.

**Comment by imhoffd** [comment]
@De-Lac I pushed out this functionality. Full usage/documentation will be in our new docs, but if you make these changes, you should see custom data (and user details) saved on the user:

``` javascript
my_custom_server_authentication(email, password)
  .then(function(user) {
    var ionic_user = {
      'user_id' : user._id,
      'details': {
        'email': email
      },
      'custom': user
    };

    var outgoingToken = jwt.sign(ionic_user, mySharedSecret);
    var url = redirectUri +
      '&token=' + encodeURIComponent(outgoingToken) +
      '&state=' + encodeURIComponent(state);
  });
```

Let me know if everything is good 👍
