### ISSUE TITLE
PHP example.

### ISSUE THREAD

**Issue by wcatron** [driftyco/custom-auth-examples#9]
I'm currently working on a php implantation of this. Would this be a welcomed example? There was enough difficulty understanding exactly how to handle the JWT token and properly generating responses, that it would fellow php devs wouldn't mind the example. Obviously php is probably low priority but I could put something together that's concise like your other examples.

**Comment by ericb** [comment]
Not low priority at all in my opinion. We'd love to see a PHP example if you wanted to put a PR together. 👍

**Comment by wcatron** [comment]
Alright, well here you go #10
